#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "${INGESTION_SCHEDULED:-False}" == "True" ]; then
    env >> /etc/environment
    service cron start
    echo "Setting up scheduled ingestion in crontab (INGESTION_SCHEDULED=True)"
    echo "${INGESTION_CRON_JOB} . /etc/environment; /usr/local/bin/python /app/manage.py ingest >> /app/cron-ingestion.log 2>&1" | crontab -
else
  echo "Ingestion not scheduled (INGESTION_SCHEDULED=False)"
fi

python manage.py migrate
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
