# Generated by Django 5.0 on 2023-12-14 12:26
from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydrologicalMetric",
            fields=[
                ("timestamp_local", models.DateTimeField(primary_key=True, serialize=False,
                                                         verbose_name="Timestamp local")),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp UTC")),

                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True, verbose_name="Minimum value"
                    ),
                ),
                ("avg_value", models.DecimalField(decimal_places=5, max_digits=15, verbose_name="Average value")),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True, verbose_name="Maximum value"
                    ),
                ),
                ("unit", models.CharField(
                    blank=True,
                    choices=[
                        ("cm", "centimeter"),
                        ("m^3/s", "cubic meters per second"),
                        ("degC", "degree celsius"),
                        ("dimensionless", "dimensionless"),
                        ("m^2", "square meter"),
                    ],
                    max_length=20,
                    verbose_name="Unit",
                ),),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("M", "Manual"),
                            ("A", "Automatic"),
                            ("C", "Calculated"),
                            ("I", "Imported"),
                            ("U", "Unknown"),
                        ],
                        default="U",
                        max_length=2,
                        verbose_name="Value type",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("WD", "Water discharge"),
                            ("WL", "Water level"),
                            ("WV", "Water velocity"),
                            ("WT", "Water temperature"),
                            ("AT", "Air temperature"),
                            ("PC", "Precipitation"),
                        ],
                        max_length=20,
                        verbose_name="Metric name",
                    ),
                ),
                ("sensor_identifier", models.CharField(blank=True, max_length=50, verbose_name="Sensor identifier")),
                ("sensor_type", models.CharField(blank=True, max_length=50, verbose_name="Sensor type")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stations.hydrologicalstation",
                        verbose_name="Station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hydrological metric",
                "verbose_name_plural": "Hydrological metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MeteorologicalMetric",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp UTC")),
                ("value", models.DecimalField(decimal_places=5, max_digits=10, verbose_name="Value")),
                (
                    "value_type",
                    models.CharField(
                        choices=[("I", "Imported"), ("U", "Unknown")],
                        default="U",
                        max_length=2,
                        verbose_name="Value type",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        choices=[("AT", "Air temperature"), ("PC", "Precipitation")],
                        max_length=20,
                        verbose_name="Metric name",
                    ),
                ),
                ("unit", models.CharField(
                    blank=True,
                    choices=[("degC", "degree celsius"), ("mm/day", "millimeters per day")],
                    max_length=20,
                    verbose_name="Unit",
                )),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stations.meteorologicalstation",
                        verbose_name="Station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meteorological metric",
                "verbose_name_plural": "Meteorological metrics",
                "ordering": ["-timestamp"],
            },
        ),
    ]
