# Generated by Django 5.0.4 on 2024-05-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_remove_norm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrologicalMetric',
            fields=[
                ('timestamp_local', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestamp local without timezone')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp with timezone')),
                ('min_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Minimum value')),
                ('avg_value', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Average value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Maximum value')),
                ('unit', models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit')),
                ('value_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('E', 'Estimated'), ('I', 'Imported'), ('U', 'Unknown')], default='U', max_length=2, verbose_name='Value type')),
                ('metric_name', models.CharField(choices=[('WLD', 'Water level daily'), ('WLDA', 'Water level daily average'), ('WLDC', 'Water level decadal'), ('WDD', 'Water discharge daily'), ('WDDA', 'Water discharge daily average'), ('WDFA', 'Water discharge fiveday average'), ('WDDCA', 'Water discharge decade average'), ('WDDCAH', 'Water discharge decade average historical'), ('WTO', 'Water temperature observation'), ('ATO', 'Air temperature observation'), ('IPO', 'Ice phenomena observation'), ('DP', 'Daily precipitation'), ('RCSA', 'River cross section area'), ('MD', 'Maximum depth')], max_length=20, verbose_name='Metric name')),
                ('sensor_identifier', models.CharField(blank=True, max_length=50, verbose_name='Sensor identifier')),
                ('sensor_type', models.CharField(blank=True, max_length=50, verbose_name='Sensor type')),
                ('value_code', models.IntegerField(blank=True, null=True, verbose_name='Value code')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.hydrologicalstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Hydrological metric',
                'verbose_name_plural': 'Hydrological metrics',
                'ordering': ['-timestamp_local'],
            },
        ),
        migrations.CreateModel(
            name='MeteorologicalMetric',
            fields=[
                ('timestamp_local', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestamp local without timezone')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp with timezone')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Value')),
                ('value_type', models.CharField(choices=[('I', 'Imported'), ('U', 'Unknown'), ('M', 'Manual')], default='U', max_length=2, verbose_name='Value type')),
                ('metric_name', models.CharField(choices=[('ATDCA', 'Air temperature decade average'), ('ATMA', 'Air temperature month average'), ('PDCA', 'Precipitation decade average'), ('PMA', 'Precipitation month average')], max_length=20, verbose_name='Metric name')),
                ('unit', models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.meteorologicalstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Meteorological metric',
                'verbose_name_plural': 'Meteorological metrics',
                'ordering': ['-timestamp_local'],
            },
        ),
        migrations.CreateModel(
            name='DischargeNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Value')),
                ('norm_type', models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal')], default='d', max_length=20, verbose_name='Norm type')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.hydrologicalstation', to_field='uuid', verbose_name='Hydrological station')),
            ],
            options={
                'verbose_name': 'Discharge norm',
                'verbose_name_plural': 'Discharge norms',
                'ordering': ['ordinal_number'],
                'indexes': [models.Index(models.F('norm_type'), name='norm_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dischargenorm',
            constraint=models.UniqueConstraint(models.F('station'), models.F('ordinal_number'), models.F('norm_type'), name='discharge_norm_unique_cn'),
        ),
    ]
