# Generated by Django 4.2.5 on 2023-09-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterVelocity",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Value"),
                ),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Water velocity metric",
                "verbose_name_plural": "Water velocity metrics",
                "indexes": [
                    models.Index(
                        models.F("station_id"),
                        models.OrderBy(models.F("timestamp"), descending=True),
                        name="water_velocity_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaterTemperature",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Value"),
                ),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Water temperature metric",
                "verbose_name_plural": "Water temperature metrics",
                "indexes": [
                    models.Index(
                        models.F("station_id"),
                        models.OrderBy(models.F("timestamp"), descending=True),
                        name="water_temperature_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaterLevel",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Value"),
                ),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Water level metric",
                "verbose_name_plural": "Water level metrics",
                "indexes": [
                    models.Index(
                        models.F("station_id"),
                        models.OrderBy(models.F("timestamp"), descending=True),
                        name="water_level_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaterDischarge",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Value"),
                ),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Water discharge metric",
                "verbose_name_plural": "Water discharge metrics",
                "indexes": [
                    models.Index(
                        models.F("station_id"),
                        models.OrderBy(models.F("timestamp"), descending=True),
                        name="water_discharge_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AirTemperature",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Value"),
                ),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Air temperature metric",
                "verbose_name_plural": "Air temperature metrics",
                "indexes": [
                    models.Index(
                        models.F("station_id"),
                        models.OrderBy(models.F("timestamp"), descending=True),
                        name="air_temperature_idx",
                    )
                ],
            },
        ),
    ]
