# Generated by Django 5.0 on 2024-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0003_create_hypertables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrologicalmetric",
            name="metric_name",
            field=models.CharField(
                choices=[
                    ("WLDM", "Water level daily measurement"),
                    ("WLADM", "Water level daily average measurement"),
                    ("WLDAE", "Water level daily average estimation"),
                    ("WDDE", "Water discharge daily estimation"),
                    ("WDDAE", "Water discharge daily average estimation"),
                    ("WDFA", "Water discharge fiveday average"),
                    ("WDDCA", "Water discharge decade average"),
                    ("WTO", "Water temperature observation"),
                    ("ATO", "Air temperature observation"),
                    ("IPO", "Ice phenomena observation"),
                    ("WDDM", "Water discharge daily measurement"),
                    ("WLDCM", "Water level decadal measurement"),
                    ("RCSAM", "River cross section area measurement"),
                    ("MDM", "Maximum Depth Measurement"),
                    ("WDDCAH", "Water discharge decade average historical"),
                ],
                max_length=20,
                verbose_name="Metric name",
            ),
        ),
        migrations.AlterField(
            model_name="meteorologicalmetric",
            name="metric_name",
            field=models.CharField(
                choices=[
                    ("ATDCA", "Air temperature decade average"),
                    ("ATMA", "Air temperature month average"),
                    ("PDCA", "Precipitation decade average"),
                    ("PMA", "Precipitation month average"),
                ],
                max_length=20,
                verbose_name="Metric name",
            ),
        ),
    ]
