# Generated by Django 5.0.4 on 2024-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_create_hypertables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='metric_name',
            field=models.CharField(choices=[('WLD', 'Water level daily'), ('WLDA', 'Water level daily average'), ('WLDC', 'Water level decadal'), ('WLDCA', 'Water level decade average'), ('WDD', 'Water discharge daily'), ('WDDA', 'Water discharge daily average'), ('WDFA', 'Water discharge fiveday average'), ('WDDCA', 'Water discharge decade average'), ('WDDCAH', 'Water discharge decade average historical'), ('WTO', 'Water temperature observation'), ('ATO', 'Air temperature observation'), ('IPO', 'Ice phenomena observation'), ('PD', 'Precipitation daily'), ('RCSA', 'River cross section area'), ('MD', 'Maximum depth')], max_length=20, verbose_name='Metric name'),
        ),
    ]
