# Generated by Django 5.0 on 2024-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_create_hypertables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='metric_name',
            field=models.CharField(choices=[('WLD', 'Water level daily'), ('WLDA', 'Water level daily average'), ('WLDC', 'Water level decadal'), ('WDD', 'Water discharge daily'), ('WDDA', 'Water discharge daily average'), ('WDFA', 'Water discharge fiveday average'), ('WDDCA', 'Water discharge decade average'), ('WDDCAH', 'Water discharge decade average historical'), ('WTO', 'Water temperature observation'), ('ATO', 'Air temperature observation'), ('IPO', 'Ice phenomena observation'), ('RCSA', 'River cross section area'), ('MD', 'Maximum depth')], max_length=20, verbose_name='Metric name'),
        ),
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='value_type',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('E', 'Estimated'), ('I', 'Imported'), ('U', 'Unknown')], default='U', max_length=2, verbose_name='Value type'),
        ),
        migrations.AlterField(
            model_name='meteorologicalmetric',
            name='metric_name',
            field=models.CharField(choices=[('ATDCA', 'Air temperature decade average'), ('ATMA', 'Air temperature month average'), ('PDCA', 'Precipitation decade average'), ('PMA', 'Precipitation month average')], max_length=20, verbose_name='Metric name'),
        ),
        migrations.AlterField(
            model_name='meteorologicalmetric',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='meteorologicalmetric',
            name='value_type',
            field=models.CharField(choices=[('I', 'Imported'), ('U', 'Unknown'), ('M', 'Manual')], default='U', max_length=2, verbose_name='Value type'),
        ),
    ]
