# Generated by Django 5.0.4 on 2024-05-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_add_water_level_decade_average_metric_name'),
        ('stations', '0004_remove_norm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Value')),
                ('norm_type', models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal')], default='d', max_length=20, verbose_name='Norm type')),
                ('norm_metric', models.CharField(choices=[('p', 'Precipitation'), ('t', 'Temperature')], default='p', max_length=2, verbose_name='Norm type')),
            ],
            options={
                'verbose_name': 'Meteorological norm',
                'verbose_name_plural': 'Meteorological norms',
                'ordering': ['ordinal_number'],
            },
        ),
        migrations.RenameModel(
            old_name='DischargeNorm',
            new_name='HydrologicalNorm',
        ),
        migrations.RenameIndex(
            model_name='hydrologicalnorm',
            new_name='discharge_norm_type_idx',
            old_name='norm_type_idx',
        ),
        migrations.AddField(
            model_name='meteorologicalnorm',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.meteorologicalstation', to_field='uuid', verbose_name='Meteorological station'),
        ),
        migrations.AddIndex(
            model_name='meteorologicalnorm',
            index=models.Index(models.F('norm_type'), name='meteo_norm_type_idx'),
        ),
        migrations.AddIndex(
            model_name='meteorologicalnorm',
            index=models.Index(models.F('norm_metric'), name='meteo_norm_metric_idx'),
        ),
        migrations.AddConstraint(
            model_name='meteorologicalnorm',
            constraint=models.UniqueConstraint(models.F('station'), models.F('ordinal_number'), models.F('norm_type'), models.F('norm_metric'), name='meteorological_norm_unique_cn'),
        ),
    ]
