# Generated by Django 5.0.4 on 2024-04-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_hydrologicalmetric_metric_name_and_more'),
        ('stations', '0004_remove_norm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Value')),
                ('norm_type', models.CharField(blank=True, choices=[('m', 'Monthly'), ('d', 'Decadal')], max_length=20, verbose_name='Norm type')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.hydrologicalstation', verbose_name='Hydrological station')),
            ],
            options={
                'verbose_name': 'Discharge norm',
                'verbose_name_plural': 'Discharge norms',
                'ordering': ['ordinal_number'],
                'indexes': [models.Index(models.F('norm_type'), name='norm_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dischargenorm',
            constraint=models.UniqueConstraint(models.F('station'), models.F('ordinal_number'), models.F('norm_type'), name='discharge_norm_unique_cn'),
        ),
    ]
