# Generated by Django 5.0.1 on 2024-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_hydrologicalmetric_metric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='meteorologicalmetric',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit'),
        ),
    ]
