# Generated by Django 5.0.4 on 2024-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_add_discharge_norm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalmetric',
            name='value_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value code'),
        ),
    ]
