# Generated by Django 5.0.4 on 2024-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_add_discharge_norm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalmetric',
            name='value_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value code'),
        ),
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='metric_name',
            field=models.CharField(choices=[('WLD', 'Water level daily'), ('WLDA', 'Water level daily average'), ('WLDC', 'Water level decadal'), ('WDD', 'Water discharge daily'), ('WDDA', 'Water discharge daily average'), ('WDFA', 'Water discharge fiveday average'), ('WDDCA', 'Water discharge decade average'), ('WDDCAH', 'Water discharge decade average historical'), ('WTO', 'Water temperature observation'), ('ATO', 'Air temperature observation'), ('IPO', 'Ice phenomena observation'), ('DP', 'Daily precipitation'), ('RCSA', 'River cross section area'), ('MD', 'Maximum depth')], max_length=20, verbose_name='Metric name'),
        ),
    ]
