# Generated by Django 5.0.4 on 2024-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_add_value_code_to_hydrological_metric_and_daily_precipiration_metric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorologicalmetric',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestamp'),
        ),
    ]
