# Generated by Django 5.0.4 on 2024-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_views_bulk_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDataHydroAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_local', models.DateTimeField()),
                ('water_level_daily_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_level_daily_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_level_daily_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('air_temperature_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('air_temperature_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('air_temperature_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_temperature_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_temperature_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_temperature_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discharge_daily_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fiveday_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
                ('decade_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'metrics_bulk_data_hydro_auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BulkDataHydroManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_local', models.DateTimeField()),
                ('water_level_daily', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_level_daily_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discharge_measurement', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discharge_daily', models.DecimalField(decimal_places=3, max_digits=10)),
                ('free_river_area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('decade_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discharge_daily_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ice_phenomena', models.CharField(blank=True, max_length=20)),
                ('water_level_measurement', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fiveday_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
                ('air_temperature', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_temperature', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precipitation_daily', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'metrics_bulk_data_hydro_manual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BulkDataMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_local', models.DateTimeField()),
                ('air_temperature_decade_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('air_temperature_month_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precipitation_decade_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precipitation_month_average', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'metrics_bulk_data_meteo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BulkDataVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_local', models.DateTimeField()),
                ('discharge_daily', models.DecimalField(decimal_places=3, max_digits=10)),
                ('decade_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discharge_daily_average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fiveday_discharge', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'metrics_bulk_data_virtual',
                'managed': False,
            },
        ),
    ]
