# Generated by Django 5.1 on 2024-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_models_bulk_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalmetric',
            name='source_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='hydrologicalmetric',
            name='source_type',
            field=models.CharField(choices=[('US', 'User'), ('TL', 'Telegram'), ('IN', 'Ingester'), ('UN', 'Unknown')], default='UN', max_length=2, verbose_name='Entry type'),
        ),
        migrations.AddField(
            model_name='meteorologicalmetric',
            name='source_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='meteorologicalmetric',
            name='source_type',
            field=models.CharField(choices=[('US', 'User'), ('TL', 'Telegram'), ('IN', 'Ingester'), ('UN', 'Unknown')], default='UN', max_length=2, verbose_name='Entry type'),
        ),
    ]
