# Generated by Django 5.1.1 on 2025-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_alter_hydrologicalmetric_metric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrologicalnorm',
            name='norm_type',
            field=models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal'), ('p', 'Pentadal')], default='d', max_length=20, verbose_name='Norm type'),
        ),
        migrations.AlterField(
            model_name='meteorologicalnorm',
            name='norm_type',
            field=models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal'), ('p', 'Pentadal')], default='d', max_length=20, verbose_name='Norm type'),
        ),
    ]
