# Generated by Django 5.1.1 on 2025-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_alter_hydrologicalnorm_norm_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrologicalmetric',
            name='value_type',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('E', 'Estimated'), ('I', 'Imported'), ('U', 'Unknown'), ('O', 'Override')], default='U', max_length=2, verbose_name='Value type'),
        ),
    ]
