# Generated by Django 5.1.1 on 2025-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_alter_hydrologicalmetric_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalnorm',
            name='norm_metric',
            field=models.CharField(choices=[('water_level', 'Water level'), ('discharge', 'Water discharge')], default='discharge', max_length=20, verbose_name='Norm metric'),
        ),
    ]
