# Generated by Django 5.1.1 on 2025-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_alter_hydrologicalmetric_value_type'),
        ('stations', '0008_hydrologicalstation_historical_water_level_maximum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrologicalnorm',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Hydrological norm', 'verbose_name_plural': 'Hydrological norms'},
        ),
        migrations.RemoveConstraint(
            model_name='hydrologicalnorm',
            name='discharge_norm_unique_cn',
        ),
        migrations.RenameIndex(
            model_name='hydrologicalnorm',
            new_name='hydrological_norm_type_idx',
            old_name='discharge_norm_type_idx',
        ),
        migrations.AddField(
            model_name='hydrologicalnorm',
            name='norm_metric',
            field=models.CharField(choices=[('water_level', 'Water level'), ('discharge', 'Water discharge')], default='discharge', max_length=20, verbose_name='Norm metric'),
        ),
        migrations.AlterField(
            model_name='meteorologicalnorm',
            name='norm_metric',
            field=models.CharField(choices=[('precipitation', 'Precipitation'), ('temperature', 'Temperature')], default='precipitation', max_length=20, verbose_name='Norm type'),
        ),
        migrations.AddIndex(
            model_name='hydrologicalnorm',
            index=models.Index(models.F('norm_metric'), name='hydrological_norm_metric_idx'),
        ),
        migrations.AddConstraint(
            model_name='hydrologicalnorm',
            constraint=models.UniqueConstraint(models.F('station'), models.F('ordinal_number'), models.F('norm_type'), models.F('norm_metric'), name='hydrological_norm_unique_cn'),
        ),
    ]
