# Generated by Django 5.1.1 on 2025-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_alter_hydrologicalmetric_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalnorm',
            name='norm_metric',
            field=models.CharField(choices=[('WL', 'Water level'), ('WD', 'Water discharge')], default='WD', max_length=5, verbose_name='Norm metric'),
        ),
    ]
