# Generated by Django 4.2.2 on 2023-06-15 11:40

from django.db import migrations, models
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Organization name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("url", models.URLField(blank=True, verbose_name="Organization URL")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("street_address", models.CharField(max_length=255, verbose_name="Street address")),
                ("zip_code", models.CharField(max_length=50, verbose_name="ZIP code")),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(blank=True, null=True, verbose_name="Organization timezone"),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=200, verbose_name="Contact person")),
                (
                    "contact_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="Contact phone"
                    ),
                ),
                (
                    "year_type",
                    models.CharField(
                        choices=[("CA", "Calendar"), ("HY", "Hydrological")],
                        default="HY",
                        max_length=2,
                        verbose_name="Year type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English"), ("RU", "Russian")],
                        default="EN",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active?")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Is deleted?")),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-name"],
            },
        ),
    ]
