# Generated by Django 5.0 on 2023-12-11 13:27

import uuid

import django.core.validators
import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=100, verbose_name="Organization name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("url", models.URLField(blank=True, verbose_name="Organization URL")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("street_address", models.CharField(max_length=255, verbose_name="Street address")),
                ("zip_code", models.CharField(max_length=50, verbose_name="ZIP code")),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(blank=True, null=True, verbose_name="Organization timezone"),
                ),
                ("contact", models.CharField(blank=True, default="", max_length=200, verbose_name="Contact person")),
                ("contact_phone", models.CharField(blank=True, max_length=100, verbose_name="Phone number")),
                (
                    "year_type",
                    models.CharField(
                        choices=[("CA", "Calendar"), ("HY", "Hydrological")],
                        default="HY",
                        max_length=2,
                        verbose_name="Year type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active?")),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-name"],
                "indexes": [models.Index(fields=["uuid"], name="organization_uuid_idx")],
            },
        ),
        migrations.CreateModel(
            name="Basin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=200, verbose_name="Basin")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basins",
                        to="organizations.organization",
                        to_field="uuid",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basin",
                "verbose_name_plural": "Basins",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=200, verbose_name="Region")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="organizations.organization",
                        to_field="uuid",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["-name"],
            },
        ),
    ]
