# Generated by Django 4.2.4 on 2023-08-10 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="UUID"),
        ),
    ]
