# Generated by Django 4.2.5 on 2023-11-15 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=200, verbose_name="Region")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="organizations.organization",
                        to_field="uuid",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Basin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=200, verbose_name="Basin")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basins",
                        to="organizations.organization",
                        to_field="uuid",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basin",
                "verbose_name_plural": "Basins",
                "ordering": ["-name"],
            },
        ),
    ]
