# Generated by Django 5.0.4 on 2024-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discharge_norm_type',
            field=models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal')], default='d', max_length=20, verbose_name='Norm type'),
        ),
    ]
