# Generated by Django 5.0.6 on 2024-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_discharge_norm_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
    ]
