# Generated by Django 5.0.6 on 2024-08-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_discharge_norm_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='bulletin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Bulletin order'),
        ),
        migrations.AddField(
            model_name='basin',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='region',
            name='bulletin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Bulletin order'),
        ),
        migrations.AddField(
            model_name='region',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
    ]
