# Generated by Django 4.2.4 on 2023-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_add_uuid_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["uuid"], name="organization_uuid_idx"),
        ),
    ]
