# Generated by Django 5.1.1 on 2025-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_secondary_name_and_bulletin_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='discharge_norm_type',
            field=models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal'), ('p', 'Pentadal')], default='d', max_length=20, verbose_name='Norm type'),
        ),
    ]
