# Generated by Django 4.2.5 on 2023-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_uuid_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")], default="en", max_length=2, verbose_name="Language"
            ),
        ),
    ]
