# Generated by Django 5.0 on 2024-02-21 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_alter_site_options_remove_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization name')),
                ('param_a', models.DecimalField(decimal_places=30, max_digits=50, verbose_name='Parameter a')),
                ('param_b', models.DecimalField(decimal_places=30, max_digits=50, verbose_name='Parameter b')),
                ('param_c', models.DecimalField(decimal_places=30, max_digits=50, verbose_name='Parameter c')),
                ('valid_from', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.hydrologicalstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Discharge model',
                'verbose_name_plural': 'Discharge models',
                'ordering': ['-valid_from'],
            },
        ),
    ]
