# Generated by Django 5.0 on 2024-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargemodel',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
    ]
