# Generated by Django 5.0.4 on 2024-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimations', '0002_create_views'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(
                """
                create or replace view  estimations_water_discharge_daily_virtual
                as
                SELECT
                    wdd.timestamp_local,
                    vsa.virtual_station_id as station_id,
                    SUM(wdd.avg_value * (vsa.weight / 100.0)) AS avg_value,
                    'm^3/s' as unit,
                    'E' as value_type,
                    wdd.metric_name
                FROM
                    estimations_water_discharge_daily wdd
                JOIN
                    stations_virtualstationassociation vsa
                ON
                    wdd.station_id = vsa.hydro_station_id
                GROUP BY
                    wdd.timestamp_local,
                    vsa.virtual_station_id,
                    wdd.metric_name;
              """
            )],
            reverse_sql=[("drop view if exists estimations_water_discharge_daily_virtual;")],
        ),

        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_water_discharge_daily_average_virtual
                as
                SELECT wdda.timestamp_local,
                       vsa.virtual_station_id                    as station_id,
                       SUM(wdda.avg_value * (vsa.weight / 100.0)) AS avg_value,
                       'm^3/s'                                   as unit,
                       'E'                                       as value_type,
                       wdda.metric_name
                FROM estimations_water_discharge_daily_average wdda
                JOIN
                     stations_virtualstationassociation vsa
                ON
                         wdda.station_id = vsa.hydro_station_id
                GROUP BY wdda.timestamp_local,
                         vsa.virtual_station_id,
                         wdda.metric_name;
              """
            )],
            reverse_sql=[("drop view if exists estimations_water_discharge_daily_average_virtual;")],
        ),

        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_water_discharge_fiveday_average_virtual
                as
                SELECT wdfa.timestamp_local,
                       vsa.virtual_station_id                     as station_id,
                       SUM(wdfa.avg_value * (vsa.weight / 100.0)) AS avg_value,
                       'm^3/s'                                    as unit,
                       'E'                                        as value_type,
                       wdfa.metric_name
                FROM estimations_water_discharge_fiveday_average wdfa
                         JOIN
                     stations_virtualstationassociation vsa
                     ON
                         wdfa.station_id = vsa.hydro_station_id
                GROUP BY wdfa.timestamp_local,
                         vsa.virtual_station_id,
                         wdfa.metric_name;

              """
            )],
            reverse_sql=[("drop view if exists estimations_water_discharge_fiveday_average_virtual;")],
        ),

        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_water_discharge_decade_average_virtual
                as
                SELECT wddca.timestamp_local,
                       vsa.virtual_station_id                     as station_id,
                       SUM(wddca.avg_value * (vsa.weight / 100.0)) AS avg_value,
                       'm^3/s'                                    as unit,
                       'E'                                        as value_type,
                       wddca.metric_name
                FROM estimations_water_discharge_decade_average wddca
                         JOIN
                     stations_virtualstationassociation vsa
                     ON
                         wddca.station_id = vsa.hydro_station_id
                GROUP BY wddca.timestamp_local,
                         vsa.virtual_station_id,
                         wddca.metric_name;
                """
            )],
            reverse_sql=[("drop view if exists estimations_water_discharge_decade_average_virtual;")],
        ),
        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_dischargenorm_virtual
                as
                WITH cte AS
                (
                SELECT dn.ordinal_number,
                        SUM(dn.value * (vsa.weight / 100.0)) AS value,
                        dn.norm_type,
                        vs.uuid                              as station_id
                 FROM metrics_dischargenorm dn
                          join stations_hydrologicalstation sh on dn.station_id = sh.uuid
                          join stations_virtualstationassociation vsa on sh.id = vsa.hydro_station_id
                          join stations_virtualstation vs on vsa.virtual_station_id = vs.id
                 group by dn.ordinal_number,
                          dn.norm_type,
                          vs.uuid
                )
                select
                    ROW_NUMBER()
                    OVER (ORDER BY ordinal_number) AS id,
                    cte.*
                FROM cte;
              """
            )],
            reverse_sql=[("drop view if exists estimations_dischargenorm_virtual;")],
        )
    ]
