# Generated by Django 5.0.4 on 2024-06-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimations', '0003_virtual_views'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_dischargenorm_virtual
                as
                WITH cte AS
                (
                SELECT dn.ordinal_number,
                        SUM(dn.value * (vsa.weight / 100.0)) AS value,
                        dn.norm_type,
                        vs.uuid                              as station_id
                 FROM metrics_dischargenorm dn
                          join stations_hydrologicalstation sh on dn.station_id = sh.uuid
                          join stations_virtualstationassociation vsa on sh.id = vsa.hydro_station_id
                          join stations_virtualstation vs on vsa.virtual_station_id = vs.id
                 group by dn.ordinal_number,
                          dn.norm_type,
                          vs.uuid
                )
                select
                    ROW_NUMBER()
                    OVER (ORDER BY ordinal_number) AS id,
                    cte.*
                FROM cte;
              """
            )],
            reverse_sql=[("drop view if exists estimations_dischargenorm_virtual;")],
        )
    ]
