# Generated by Django 5.0.4 on 2024-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimations', '0003_virtual_views'),
        ('metrics', '0005_meteo_norm_model'),

    ]

    operations = [
        migrations.RunSQL(
            sql=[(
                """
                create or replace view estimations_hydrologicalnorm_virtual
                as
                WITH cte AS
                (
                SELECT hn.ordinal_number,
                        hydrological_round(SUM(hn.value * (vsa.weight / 100.0))) AS value,
                        hn.norm_type,
                        vs.uuid                              as station_id
                 FROM metrics_hydrologicalnorm hn
                          join stations_hydrologicalstation sh on hn.station_id = sh.uuid
                          join stations_virtualstationassociation vsa on sh.id = vsa.hydro_station_id
                          join stations_virtualstation vs on vsa.virtual_station_id = vs.id
                 group by hn.ordinal_number,
                          hn.norm_type,
                          vs.uuid
                )
                select
                    ROW_NUMBER()
                    OVER (ORDER BY ordinal_number) AS id,
                    cte.*
                FROM cte;
              """
            )],
            reverse_sql=[("drop view if exists estimations_hydrologicalnorm_virtual;")],
        ),
        migrations.CreateModel(
            name='HydrologicalNormVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Value')),
                ('norm_type', models.CharField(choices=[('m', 'Monthly'), ('d', 'Decadal')], default='d', max_length=20,
                                               verbose_name='Norm type')),
            ],
            options={
                'db_table': 'estimations_hydrologicalnorm_virtual',
                'managed': False,
            },
        ),
    ]
