# Generated by Django 5.1.1 on 2025-03-23 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0006_estimationsairtemperaturedaily_and_more'),
        ('stations', '0007_add_chart_settings_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeCalculationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('start_date_local', models.DateTimeField(verbose_name='Start Date')),
                ('end_date_local', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('state', models.CharField(choices=[('MANUAL', 'Manual Discharge'), ('SUSPENDED', 'No Calculation')], max_length=20, verbose_name='Calculation State')),
                ('reason', models.CharField(choices=[('ICE', 'Ice Phenomena'), ('PRIVODKA', 'Privodka'), ('STATION_CLOSED', 'Station Closed'), ('OTHER', 'Other')], max_length=20, verbose_name='Reason')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_calculation_periods', to='stations.hydrologicalstation', verbose_name='Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_calculation_periods', to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Discharge Calculation Period',
                'verbose_name_plural': 'Discharge Calculation Periods',
                'ordering': ['-start_date_local'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date_local__isnull', True), ('end_date_local__gt', models.F('start_date_local')), _connector='OR'), name='end_date_local__after_start_date_local')],
            },
        ),
    ]
