# Generated by Django 5.1.1 on 2025-03-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0007_dischargecalculationperiod'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS metrics_bulk_data_hydro_manual;
            DROP VIEW IF EXISTS metrics_bulk_data_virtual;
            DROP VIEW IF EXISTS metrics_bulk_data_hydro_auto;
            DROP VIEW IF EXISTS estimations_water_discharge_fiveday_average_virtual;
            DROP VIEW IF EXISTS estimations_water_discharge_decade_average_virtual;
            DROP VIEW IF EXISTS estimations_water_discharge_fiveday_average;
            DROP VIEW IF EXISTS estimations_water_discharge_decade_average;
            DROP VIEW IF EXISTS estimations_water_discharge_daily_virtual;
            DROP VIEW IF EXISTS estimations_water_discharge_daily_average_virtual;
            DROP VIEW IF EXISTS estimations_water_discharge_daily_average;
            DROP VIEW IF EXISTS estimations_water_discharge_daily;
            DROP VIEW IF EXISTS estimations_water_level_decade_average;
            """,
            reverse_sql="""
            CREATE OR REPLACE VIEW estimations_water_level_decade_average AS
                WITH data_ranges AS (
                    SELECT wlda.timestamp_local,
                           wlda.station_id,
                           wlda.value_type,
                           CASE
                               WHEN EXTRACT(DAY FROM wlda.timestamp_local) BETWEEN 1 AND 10 THEN 'first_decade'
                               WHEN EXTRACT(DAY FROM wlda.timestamp_local) BETWEEN 11 AND 20 THEN 'second_decade'
                               ELSE 'third_decade'
                           END AS decade,
                           wlda.avg_value
                    FROM public.estimations_water_level_daily_average wlda
                ),
                decade_averages AS (
                    SELECT station_id,
                           EXTRACT(YEAR FROM timestamp_local) AS year,
                           EXTRACT(MONTH FROM timestamp_local) AS month,
                           decade,
                           CASE 
                               WHEN value_type = 'A' THEN ROUND(AVG(avg_value), 1)
                               ELSE CEIL(AVG(avg_value))
                           END AS avg_value
                    FROM data_ranges
                    GROUP BY station_id, year, month, decade, value_type
                ),
                representative_days AS (
                            SELECT
                                station_id,
                                year,
                                month,
                                decade,
                                avg_value,
                                -- Set the representative day manually
                                TO_TIMESTAMP(
                                    year || '-' || month || '-' ||
                                    CASE
                                        WHEN decade = 'first_decade' THEN '05'
                                        WHEN decade = 'second_decade' THEN '15'
                                        ELSE '25'
                                    END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                                ) AS representative_timestamp
                            FROM decade_averages
                        )
                SELECT representative_timestamp AS timestamp_local,
                       CAST(NULL AS NUMERIC) AS min_value,
                       avg_value,
                       CAST(NULL AS NUMERIC) AS max_value,
                       'cm' AS unit,
                       'E' AS value_type,
                       'WLDCA' AS metric_name,
                       '' AS sensor_identifier,
                       '' AS sensor_type,
                       station_id
                FROM representative_days;
            
            create or replace view estimations_water_discharge_daily as
                SELECT
                    wld.timestamp_local ,
                    CAST(NULL AS NUMERIC) as min_value,
                    hydrological_round(dm.param_c * POWER((wld.avg_value + dm.param_a), dm.param_b)) AS avg_value,
                    CAST(NULL AS NUMERIC) as max_value,
                    'm^3/s' as unit,
                    'E' as value_type,
                    'WDD' as metric_name,
                    '' as sensor_identifier,
                    '' as sensor_type,
                    wld.station_id
                FROM
                    metrics_hydrologicalmetric wld
                JOIN (
                    SELECT
                        dm.*,
                        LEAD(valid_from_local) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_valid_from_local,
                        LEAD(name) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_model_name,
                        LEAD(station_id) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_site_id
                    FROM
                        estimations_dischargemodel dm
                ) dm ON wld.timestamp_local >= dm.valid_from_local AND (wld.timestamp_local < dm.next_valid_from_local OR dm.next_valid_from_local IS NULL) AND wld.station_id = dm.station_id
                WHERE
                    wld.metric_name = 'WLD' and wld.value_type='M';

            create or replace view estimations_water_discharge_daily_average as
                SELECT
                    wlda.timestamp_local,
                    CAST(NULL AS NUMERIC) as min_value,
                    hydrological_round(dm.param_c * POWER((wlda.avg_value + dm.param_a), dm.param_b)) AS avg_value,
                    CAST(NULL AS NUMERIC) as max_value,
                    'm^3/s' as unit,
                    'E' as value_type,
                    'WDDA' as metric_name,
                    '' as sensor_identifier,
                    '' as sensor_type,
                    wlda.station_id
                FROM
                    estimations_water_level_daily_average wlda
                JOIN (
                    SELECT
                        dm.*,
                        LEAD(valid_from_local) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_valid_from_local,
                        LEAD(name) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_model_name,
                        LEAD(station_id) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_site_id
                    FROM
                        estimations_dischargemodel dm
                ) dm ON wlda.timestamp_local >= dm.valid_from_local AND (wlda.timestamp_local < dm.next_valid_from_local OR dm.next_valid_from_local IS NULL) AND wlda.station_id = dm.station_id
                WHERE
                    wlda.metric_name = 'WLDA';

            CREATE OR REPLACE VIEW estimations_water_discharge_fiveday_average AS
            WITH data_ranges AS (
                    SELECT wdda.timestamp_local,
                            wdda.station_id,
                            CASE
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 1 AND 5 THEN 'first_pentad'
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 6 AND 10 THEN 'second_pentad'
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 11 AND 15 THEN 'third_pentad'
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 16 AND 20 THEN 'fourth_pentad'
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 21 AND 25 THEN 'fifth_pentad'
                                ELSE 'sixth_pentad'
                            END AS pentad,
                            wdda.avg_value
                    FROM public.estimations_water_discharge_daily_average wdda
                ),
                pentad_averages AS (
                    SELECT station_id,
                            EXTRACT(YEAR FROM timestamp_local) AS year,
                            EXTRACT(MONTH FROM timestamp_local) AS month,
                            pentad,
                            hydrological_round(AVG(avg_value)) AS avg_value
                    FROM data_ranges
                    GROUP BY station_id, year, month, pentad
                ),
                representative_days AS (
                        SELECT
                            station_id,
                            year,
                            month,
                            pentad,
                            avg_value,
                            -- Set the representative day manually
                            TO_TIMESTAMP(
                                year || '-' || month || '-' ||
                                CASE
                                    WHEN pentad = 'first_pentad' THEN 3
                                    WHEN pentad = 'second_pentad' THEN 8
                                    WHEN pentad = 'third_pentad' THEN 13
                                    WHEN pentad = 'fourth_pentad' THEN 18
                                    WHEN pentad = 'fifth_pentad' THEN 23
                                    ELSE 28
                                END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                            ) AS representative_timestamp
                        FROM pentad_averages
                    )
                SELECT representative_timestamp AS timestamp_local,
                        CAST(NULL AS NUMERIC) AS min_value,
                        avg_value,
                        CAST(NULL AS NUMERIC) AS max_value,
                        'm^3/s' AS unit,
                        'E' AS value_type,
                        'WDFA' AS metric_name,
                        '' AS sensor_identifier,
                        '' AS sensor_type,
                        station_id
                FROM representative_days;
            
            CREATE OR REPLACE VIEW estimations_water_discharge_decade_average AS
                    WITH data_ranges AS (
                        SELECT wdda.timestamp_local,
                                wdda.station_id,
                                CASE
                                    WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 1 AND 10 THEN 'first_decade'
                                    WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 11 AND 20 THEN 'second_decade'
                                    ELSE 'third_decade'
                                END AS decade,
                                wdda.avg_value
                        FROM public.estimations_water_discharge_daily_average wdda
                    ),
                    decade_averages AS (
                        SELECT station_id,
                                EXTRACT(YEAR FROM timestamp_local) AS year,
                                EXTRACT(MONTH FROM timestamp_local) AS month,
                                decade,
                                hydrological_round(AVG(avg_value)) AS avg_value
                        FROM data_ranges
                        GROUP BY station_id, year, month, decade
                    ),
                    representative_days AS (
                        SELECT
                            station_id,
                            year,
                            month,
                            decade,
                            avg_value,
                            -- Set the representative day manually
                            TO_TIMESTAMP(
                                year || '-' || month || '-' ||
                                CASE
                                    WHEN decade = 'first_decade' THEN '05'
                                    WHEN decade = 'second_decade' THEN '15'
                                    ELSE '25'
                                END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                            ) AS representative_timestamp
                        FROM decade_averages
                    )
                    SELECT representative_timestamp AS timestamp_local,
                            CAST(NULL AS NUMERIC) AS min_value,
                            avg_value,
                            CAST(NULL AS NUMERIC) AS max_value,
                            'm^3/s' AS unit,
                            'E' AS value_type,
                            'WDDCA' AS metric_name,
                            '' AS sensor_identifier,
                            '' AS sensor_type,
                            station_id
                    FROM representative_days;

            create or replace view  estimations_water_discharge_daily_virtual
                as
                SELECT
                    wdd.timestamp_local,
                    vsa.virtual_station_id as station_id,
                    hydrological_round(SUM(wdd.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s' as unit,
                    'E' as value_type,
                    wdd.metric_name
                FROM
                    estimations_water_discharge_daily wdd
                JOIN
                    stations_virtualstationassociation vsa
                ON
                    wdd.station_id = vsa.hydro_station_id
                GROUP BY
                    wdd.timestamp_local,
                    vsa.virtual_station_id,
                    wdd.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );

            create or replace view estimations_water_discharge_daily_average_virtual
                as
                SELECT wdda.timestamp_local,
                    vsa.virtual_station_id                    as station_id,
                    hydrological_round(SUM(wdda.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s'                                   as unit,
                    'E'                                       as value_type,
                    wdda.metric_name
                FROM estimations_water_discharge_daily_average wdda
                JOIN
                    stations_virtualstationassociation vsa
                ON
                        wdda.station_id = vsa.hydro_station_id
                GROUP BY wdda.timestamp_local,
                        vsa.virtual_station_id,
                        wdda.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );
            create or replace view estimations_water_discharge_fiveday_average_virtual
                as
                SELECT wdfa.timestamp_local,
                    vsa.virtual_station_id                     as station_id,
                    hydrological_round(SUM(wdfa.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s'                                    as unit,
                    'E'                                        as value_type,
                    wdfa.metric_name
                FROM estimations_water_discharge_fiveday_average wdfa
                        JOIN
                    stations_virtualstationassociation vsa
                    ON
                        wdfa.station_id = vsa.hydro_station_id
                GROUP BY wdfa.timestamp_local,
                        vsa.virtual_station_id,
                        wdfa.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );
            create or replace view estimations_water_discharge_decade_average_virtual
                as
                SELECT wddca.timestamp_local,
                    vsa.virtual_station_id                     as station_id,
                    hydrological_round(SUM(wddca.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s'                                    as unit,
                    'E'                                        as value_type,
                    wddca.metric_name
                FROM estimations_water_discharge_decade_average wddca
                        JOIN
                    stations_virtualstationassociation vsa
                    ON
                        wddca.station_id = vsa.hydro_station_id
                GROUP BY wddca.timestamp_local,
                        vsa.virtual_station_id,
                        wddca.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );
            CREATE OR REPLACE VIEW metrics_bulk_data_hydro_auto AS
                SELECT station_id,
                    timestamp_local::timestamp without time zone,
                    MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN min_value END)   AS water_level_daily_min,
                    MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN avg_value END)   AS water_level_daily_average,
                    MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN max_value END)   AS water_level_daily_max,
                    MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN min_value END)   AS air_temperature_min,
                    MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN avg_value END)   AS air_temperature_average,
                    MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN max_value END)   AS air_temperature_max,
                    MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN min_value END)   AS water_temperature_min,
                    MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN avg_value END)   AS water_temperature_average,
                    MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN max_value END)   AS water_temperature_max,
                    MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END)  AS discharge_daily_average,
                    MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge,
                    MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                    FROM metrics_hydrologicalmetric
                    WHERE value_type = 'A'
                        and metric_name in ('WLD', 'WTO', 'ATO')
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                    FROM estimations_water_discharge_daily_average
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                    FROM estimations_water_discharge_fiveday_average
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                    FROM estimations_water_discharge_decade_average) AS sub
                where station_id IN (select distinct id from stations_hydrologicalstation where station_type = 'A')
                GROUP BY station_id, timestamp_local::timestamp without time zone;
            CREATE OR REPLACE VIEW metrics_bulk_data_virtual AS
                SELECT station_id,
                        timestamp_local::timestamp without time zone,
                        MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'E' THEN avg_value END)   AS discharge_daily,
                        MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge,
                        MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END) AS discharge_daily_average,
                        MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_daily_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_daily_average_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_fiveday_average_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_decade_average_virtual) AS sub
                GROUP BY station_id, timestamp_local::timestamp without time zone;
            CREATE OR REPLACE VIEW metrics_bulk_data_hydro_manual AS
                SELECT station_id,
                    timestamp_local::timestamp without time zone, -- Convert timestamp_local to timestamp without timezone
                    MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'M' THEN avg_value END)   AS water_level_daily,
                    MAX(CASE WHEN metric_name = 'WLDA' AND value_type = 'E' THEN avg_value END)  AS water_level_daily_average,
                    MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'M' THEN avg_value END)   AS discharge_measurement,
                    MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'E' THEN avg_value END)   AS discharge_daily,
                    MAX(CASE WHEN metric_name = 'RCSA' AND value_type = 'M' THEN avg_value END)  AS free_river_area,
                    MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge,
                    MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END)  AS discharge_daily_average,
                    MAX(CASE
                            WHEN metric_name = 'IPO' AND value_type = 'M'
                                THEN value_code || ':' || avg_value::text END)                   AS ice_phenomena,
                    MAX(CASE WHEN metric_name = 'WLDC' AND value_type = 'M' THEN avg_value END)  AS water_level_measurement,
                    MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge,
                            MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'M' THEN avg_value END)  AS air_temperature,
                    MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'M' THEN avg_value END)  AS water_temperature,
                    MAX(CASE
                            WHEN metric_name = 'PD' AND value_type = 'M'
                                THEN value_code || ':' || avg_value::text END)                   AS precipitation_daily
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, avg_value, value_code
                    FROM metrics_hydrologicalmetric
                    WHERE value_type = 'M'
                        and metric_name in ('WLD', 'RCSA', 'IPO', 'WTO', 'ATO', 'PD')
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                    FROM estimations_water_discharge_daily
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                    FROM estimations_water_level_daily_average
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                    FROM estimations_water_discharge_daily_average
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                    FROM estimations_water_discharge_fiveday_average
                    UNION ALL
                    SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                    FROM estimations_water_discharge_decade_average) AS sub
                where station_id IN (select distinct id from stations_hydrologicalstation where station_type = 'M')
                GROUP BY station_id, timestamp_local::timestamp without time zone;
                """
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_level_daily_average_with_periods AS
            SELECT
                wlda.timestamp_local,
                wlda.min_value,
                wlda.avg_value,
                wlda.max_value,
                wlda.unit,
                wlda.value_type,
                wlda.metric_name,
                wlda.sensor_identifier,
                wlda.sensor_type,
                wlda.station_id
            FROM estimations_water_level_daily_average wlda
            WHERE NOT EXISTS (
                SELECT 1
                FROM public.estimations_dischargecalculationperiod edp
                WHERE edp.station_id = wlda.station_id
                AND edp.is_active = TRUE
                AND (
                -- Suspended period: exclude if ANY measurement is inside
                (edp.state = 'SUSPENDED' AND (
                    (wlda.timestamp_local::date + INTERVAL '08:00' >= edp.start_date_local
                    AND wlda.timestamp_local::date + INTERVAL '08:00' < COALESCE(edp.end_date_local, 'infinity'))
                    OR
                    (wlda.timestamp_local::date + INTERVAL '20:00' >= edp.start_date_local
                    AND wlda.timestamp_local::date + INTERVAL '20:00' < COALESCE(edp.end_date_local, 'infinity'))
                ))
                OR
                -- Manual PRIVODKA calculation: exclude ONLY the first day
                (edp.state = 'MANUAL' AND edp.reason = 'PRIVODKA'
                AND wlda.timestamp_local::date = edp.start_date_local::date)
                )
            );

            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_level_daily_average_with_periods;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_model AS
                SELECT
                wld.timestamp_local ,
                CAST(NULL AS NUMERIC) as min_value,
                hydrological_round(dm.param_c * POWER((wld.avg_value + dm.param_a), dm.param_b)) AS avg_value,
                CAST(NULL AS NUMERIC) as max_value,
                'm^3/s' as unit,
                'E' as value_type,
                'WDD' as metric_name,
                '' as sensor_identifier,
                '' as sensor_type,
                wld.station_id,
                dm.id as model_id
                FROM
                metrics_hydrologicalmetric wld
                JOIN (
                SELECT
                    dm.*,
                    LEAD(valid_from_local) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_valid_from_local,
                    LEAD(name) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_model_name,
                    LEAD(station_id) OVER (PARTITION BY station_id ORDER BY valid_from_local) AS next_site_id
                FROM
                    estimations_dischargemodel dm
                ) dm ON wld.timestamp_local >= dm.valid_from_local AND (wld.timestamp_local < dm.next_valid_from_local OR dm.next_valid_from_local IS NULL) AND wld.station_id = dm.station_id
                WHERE
                wld.metric_name = 'WLD'
                AND wld.value_type = 'M';
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_model;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_overrides AS
            SELECT
                mh.timestamp_local,
                CAST(NULL AS NUMERIC) as min_value,
                hydrological_round(mh.avg_value)  AS avg_value,
                CAST(NULL AS NUMERIC) as max_value,
                'm^3/s'    AS unit,
                'O'      AS value_type,
                'WDD'     AS metric_name,
                ''       AS sensor_identifier,
                ''       AS sensor_type,
                mh.station_id,
                0      AS model_id
            FROM public.metrics_hydrologicalmetric mh
            JOIN public.estimations_dischargecalculationperiod edp
                ON edp.station_id = mh.station_id
                AND edp.is_active = TRUE
                AND edp.state   = 'MANUAL'
                AND mh.metric_name = 'WDD'
                AND mh.value_type = 'O'
                AND mh.timestamp_local >= edp.start_date_local
                AND mh.timestamp_local < COALESCE(edp.end_date_local, 'infinity');
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_overrides;"
            ), 
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily AS
            SELECT * FROM estimations_water_discharge_daily_overrides

            UNION ALL

            SELECT m.*
            FROM estimations_water_discharge_daily_model m
            WHERE NOT EXISTS (
            SELECT 1
            FROM public.estimations_dischargecalculationperiod edp
            WHERE edp.station_id = m.station_id
                AND edp.is_active = TRUE
                AND m.timestamp_local >= edp.start_date_local
                AND m.timestamp_local < COALESCE(edp.end_date_local, 'infinity')
            );
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_average_model AS
            SELECT
            wldawp.timestamp_local,
            CAST(NULL AS NUMERIC) AS min_value,
            hydrological_round(
                dm.param_c * POWER((wldawp.avg_value + dm.param_a), dm.param_b)
            ) AS avg_value,
            CAST(NULL AS NUMERIC) AS max_value,
            'm^3/s'   AS unit,
            'E'     AS value_type,
            'WDDA'   AS metric_name,
            ''     AS sensor_identifier,
            ''     AS sensor_type,
            wldawp.station_id
            FROM estimations_water_level_daily_average_with_periods wldawp
            JOIN (
            SELECT
                dm.*,
                LEAD(valid_from_local)
                OVER (PARTITION BY station_id ORDER BY valid_from_local)
                AS next_valid_from_local
            FROM estimations_dischargemodel dm
            ) dm
            ON wldawp.station_id = dm.station_id
            AND wldawp.timestamp_local >= dm.valid_from_local
            AND (wldawp.timestamp_local < dm.next_valid_from_local
                OR dm.next_valid_from_local IS NULL)
            WHERE wldawp.metric_name = 'WLDA';
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_average_model;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_average_computed AS
            SELECT
                time_bucket('1 day', timestamp_local) at time zone 'UTC' + '12 hours' as timestamp_local,
                CAST(NULL AS NUMERIC)         AS min_value,
                AVG(avg_value)            AS avg_value,
                CAST(NULL AS NUMERIC)         AS max_value,
                'm^3/s'                AS unit,
                'E'                  AS value_type,
                'WDDA'                AS metric_name,
                ''                  AS sensor_identifier,
                ''                  AS sensor_type,
                station_id
            FROM estimations_water_discharge_daily
            GROUP BY
                station_id,
                time_bucket('1 day', timestamp_local)
            HAVING
                COUNT(DISTINCT model_id) > 1;
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_average_computed;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_average_overrides AS
            SELECT
                time_bucket('1 day', mh.timestamp_local) AT TIME ZONE 'UTC' + '12 hours' AS timestamp_local,
                NULL::NUMERIC                  AS min_value,
                AVG(mh.avg_value)                AS avg_value,
                NULL::NUMERIC                  AS max_value,
                'm^3/s'                     AS unit,
                'E'                       AS value_type,
                'WDDA'                      AS metric_name,
                ''                        AS sensor_identifier,
                ''                        AS sensor_type,
                mh.station_id
            FROM public.metrics_hydrologicalmetric mh
            JOIN public.estimations_dischargecalculationperiod edp
                ON edp.station_id  = mh.station_id
                AND edp.is_active   = TRUE
                AND edp.state     = 'MANUAL'
                AND mh.metric_name  = 'WDD'
                AND mh.value_type  = 'O'
                AND mh.timestamp_local >= edp.start_date_local
                AND mh.timestamp_local < COALESCE(edp.end_date_local, 'infinity')
            GROUP BY 1, mh.station_id
            HAVING COUNT(*) >= 2;
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_average_overrides;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_daily_average AS
            SELECT
                m.timestamp_local,
                m.min_value,
                COALESCE(
                    c.avg_value,              -- 1. true mean when multiple model/override points
                    o.avg_value,              -- 2. operator overrides, if ≥2
                    m.avg_value               -- 3. single-curve model average
                ) AS avg_value,
                m.max_value,
                m.unit,
                m.value_type,
                m.metric_name,
                m.sensor_identifier,
                m.sensor_type,
                m.station_id
            FROM estimations_water_discharge_daily_average_model m
            LEFT JOIN estimations_water_discharge_daily_average_overrides o
                ON o.station_id   = m.station_id
                AND o.timestamp_local = m.timestamp_local
            LEFT JOIN estimations_water_discharge_daily_average_computed c
                ON m.station_id   = c.station_id
                AND m.timestamp_local = c.timestamp_local
            WHERE
                -- keep days with a computed or override average
                c.avg_value IS NOT NULL
            OR o.avg_value IS NOT NULL
                -- or days with no overlapping SUSPENDED or MANUAL period
            OR NOT EXISTS (
                SELECT 1
                FROM public.estimations_dischargecalculationperiod edp
                WHERE edp.station_id    = m.station_id
                    AND edp.is_active     = TRUE
                    -- overlap check: period intersects the 24 h bucket around timestamp_local
                    AND edp.start_date_local
                        <  m.timestamp_local + INTERVAL '12 hours'
                    AND COALESCE(edp.end_date_local, 'infinity')
                        >  m.timestamp_local - INTERVAL '12 hours'
            );
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_average;"
            ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_fiveday_average AS
                WITH data_ranges AS (
                        SELECT wdda.timestamp_local,
                               wdda.station_id,
                               CASE
                                   WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 1 AND 5 THEN 'first_pentad'
                                   WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 6 AND 10 THEN 'second_pentad'
                                   WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 11 AND 15 THEN 'third_pentad'
                                   WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 16 AND 20 THEN 'fourth_pentad'
                                   WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 21 AND 25 THEN 'fifth_pentad'
                                   ELSE 'sixth_pentad'
                               END AS pentad,
                               wdda.avg_value
                        FROM public.estimations_water_discharge_daily_average wdda
                    ),
                    pentad_averages AS (
                        SELECT station_id,
                               EXTRACT(YEAR FROM timestamp_local) AS year,
                               EXTRACT(MONTH FROM timestamp_local) AS month,
                               pentad,
                               hydrological_round(AVG(avg_value)) AS avg_value
                        FROM data_ranges
                        GROUP BY station_id, year, month, pentad
                    ),
                    representative_days AS (
                            SELECT
                                station_id,
                                year,
                                month,
                                pentad,
                                avg_value,
                                -- Set the representative day manually
                                TO_TIMESTAMP(
                                    year || '-' || month || '-' ||
                                    CASE
                                        WHEN pentad = 'first_pentad' THEN 3
                                        WHEN pentad = 'second_pentad' THEN 8
                                        WHEN pentad = 'third_pentad' THEN 13
                                        WHEN pentad = 'fourth_pentad' THEN 18
                                        WHEN pentad = 'fifth_pentad' THEN 23
                                        ELSE 28
                                    END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                                ) AS representative_timestamp
                            FROM pentad_averages
                        )
                    SELECT representative_timestamp AS timestamp_local,
                           CAST(NULL AS NUMERIC) AS min_value,
                           avg_value,
                           CAST(NULL AS NUMERIC) AS max_value,
                           'm^3/s' AS unit,
                           'E' AS value_type,
                           'WDFA' AS metric_name,
                           '' AS sensor_identifier,
                           '' AS sensor_type,
                           station_id
                    FROM representative_days;
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_fiveday_average;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_discharge_decade_average AS
                WITH data_ranges AS (
                    SELECT wdda.timestamp_local,
                            wdda.station_id,
                            CASE
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 1 AND 10 THEN 'first_decade'
                                WHEN EXTRACT(DAY FROM wdda.timestamp_local) BETWEEN 11 AND 20 THEN 'second_decade'
                                ELSE 'third_decade'
                            END AS decade,
                            wdda.avg_value
                    FROM public.estimations_water_discharge_daily_average wdda
                ),
                decade_averages AS (
                    SELECT station_id,
                            EXTRACT(YEAR FROM timestamp_local) AS year,
                            EXTRACT(MONTH FROM timestamp_local) AS month,
                            decade,
                            hydrological_round(AVG(avg_value)) AS avg_value
                    FROM data_ranges
                    GROUP BY station_id, year, month, decade
                ),
                representative_days AS (
                    SELECT
                        station_id,
                        year,
                        month,
                        decade,
                        avg_value,
                        -- Set the representative day manually
                        TO_TIMESTAMP(
                            year || '-' || month || '-' ||
                            CASE
                                WHEN decade = 'first_decade' THEN '05'
                                WHEN decade = 'second_decade' THEN '15'
                                ELSE '25'
                            END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                        ) AS representative_timestamp
                    FROM decade_averages
                )
                SELECT representative_timestamp AS timestamp_local,
                        CAST(NULL AS NUMERIC) AS min_value,
                        avg_value,
                        CAST(NULL AS NUMERIC) AS max_value,
                        'm^3/s' AS unit,
                        'E' AS value_type,
                        'WDDCA' AS metric_name,
                        '' AS sensor_identifier,
                        '' AS sensor_type,
                        station_id
                FROM representative_days;
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_decade_average;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW estimations_water_level_decade_average AS
                WITH data_ranges AS (
                    SELECT wldawp.timestamp_local,
                           wldawp.station_id,
                           wldawp.value_type,
                           CASE
                               WHEN EXTRACT(DAY FROM wldawp.timestamp_local) BETWEEN 1 AND 10 THEN 'first_decade'
                               WHEN EXTRACT(DAY FROM wldawp.timestamp_local) BETWEEN 11 AND 20 THEN 'second_decade'
                               ELSE 'third_decade'
                           END AS decade,
                           wldawp.avg_value
                    FROM public.estimations_water_level_daily_average_with_periods wldawp
                ),
                decade_averages AS (
                    SELECT station_id,
                           EXTRACT(YEAR FROM timestamp_local) AS year,
                           EXTRACT(MONTH FROM timestamp_local) AS month,
                           decade,
                           CASE 
                               WHEN value_type = 'A' THEN ROUND(AVG(avg_value), 1)
                               ELSE CEIL(AVG(avg_value))
                           END AS avg_value
                    FROM data_ranges
                    GROUP BY station_id, year, month, decade, value_type
                ),
                representative_days AS (
                            SELECT
                                station_id,
                                year,
                                month,
                                decade,
                                avg_value,
                                -- Set the representative day manually
                                TO_TIMESTAMP(
                                    year || '-' || month || '-' ||
                                    CASE
                                        WHEN decade = 'first_decade' THEN '05'
                                        WHEN decade = 'second_decade' THEN '15'
                                        ELSE '25'
                                    END || ' 12:00:00', 'YYYY-MM-DD HH24:MI:SS'
                                ) AS representative_timestamp
                            FROM decade_averages
                        )
                SELECT representative_timestamp AS timestamp_local,
                       CAST(NULL AS NUMERIC) AS min_value,
                       avg_value,
                       CAST(NULL AS NUMERIC) AS max_value,
                       'cm' AS unit,
                       'E' AS value_type,
                       'WLDCA' AS metric_name,
                       '' AS sensor_identifier,
                       '' AS sensor_type,
                       station_id
                FROM representative_days;
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_level_decade_average;"
        ),
        migrations.RunSQL(
            """
            create or replace view  estimations_water_discharge_daily_virtual
                as
                SELECT
                    wdd.timestamp_local,
                    vsa.virtual_station_id as station_id,
                    hydrological_round(SUM(wdd.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s' as unit,
                    'E' as value_type,
                    wdd.metric_name
                FROM
                    estimations_water_discharge_daily wdd
                JOIN
                    stations_virtualstationassociation vsa
                ON
                    wdd.station_id = vsa.hydro_station_id
                GROUP BY
                    wdd.timestamp_local,
                    vsa.virtual_station_id,
                    wdd.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_virtual;"
        ),
        migrations.RunSQL(
            """
            create or replace view estimations_water_discharge_daily_average_virtual
                as
                SELECT wdda.timestamp_local,
                       vsa.virtual_station_id                    as station_id,
                       hydrological_round(SUM(wdda.avg_value * (vsa.weight / 100.0))) AS avg_value,
                       'm^3/s'                                   as unit,
                       'E'                                       as value_type,
                       wdda.metric_name
                FROM estimations_water_discharge_daily_average wdda
                JOIN
                     stations_virtualstationassociation vsa
                ON
                         wdda.station_id = vsa.hydro_station_id
                GROUP BY wdda.timestamp_local,
                         vsa.virtual_station_id,
                         wdda.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    );
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_daily_average_virtual;"
        ),
        migrations.RunSQL(
            """
            create or replace view estimations_water_discharge_fiveday_average_virtual
                as
                SELECT wdfa.timestamp_local,
                       vsa.virtual_station_id                     as station_id,
                       hydrological_round(SUM(wdfa.avg_value * (vsa.weight / 100.0))) AS avg_value,
                       'm^3/s'                                    as unit,
                       'E'                                        as value_type,
                       wdfa.metric_name
                FROM estimations_water_discharge_fiveday_average wdfa
                         JOIN
                     stations_virtualstationassociation vsa
                     ON
                         wdfa.station_id = vsa.hydro_station_id
                GROUP BY wdfa.timestamp_local,
                         vsa.virtual_station_id,
                         wdfa.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    )
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_fiveday_average_virtual;"
        ),
        migrations.RunSQL(
            """
            create or replace view estimations_water_discharge_decade_average_virtual
                as
                SELECT wddca.timestamp_local,
                    vsa.virtual_station_id                     as station_id,
                    hydrological_round(SUM(wddca.avg_value * (vsa.weight / 100.0))) AS avg_value,
                    'm^3/s'                                    as unit,
                    'E'                                        as value_type,
                    wddca.metric_name
                FROM estimations_water_discharge_decade_average wddca
                        JOIN
                    stations_virtualstationassociation vsa
                    ON
                        wddca.station_id = vsa.hydro_station_id
                GROUP BY wddca.timestamp_local,
                        vsa.virtual_station_id,
                        wddca.metric_name
                HAVING
                    COUNT(DISTINCT vsa.hydro_station_id) = (
                        SELECT COUNT(*)
                        FROM stations_virtualstationassociation
                        WHERE virtual_station_id = vsa.virtual_station_id
                    )
            """,
            reverse_sql="DROP VIEW IF EXISTS estimations_water_discharge_decade_average_virtual;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW metrics_bulk_data_hydro_manual AS
                SELECT station_id,
                       timestamp_local::timestamp without time zone, -- Convert timestamp_local to timestamp without timezone
                       MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'M' THEN avg_value END)   AS water_level_daily,
                       MAX(CASE WHEN metric_name = 'WLDA' AND value_type = 'E' THEN avg_value END)  AS water_level_daily_average,
                       MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'M' THEN avg_value END)   AS discharge_measurement,
                       MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'E' THEN avg_value END)   AS discharge_daily,
                       MAX(CASE WHEN metric_name = 'RCSA' AND value_type = 'M' THEN avg_value END)  AS free_river_area,
                       MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge,
                       MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END)  AS discharge_daily_average,
                       MAX(CASE
                               WHEN metric_name = 'IPO' AND value_type = 'M'
                                   THEN value_code || ':' || avg_value::text END)                   AS ice_phenomena,
                       MAX(CASE WHEN metric_name = 'WLDC' AND value_type = 'M' THEN avg_value END)  AS water_level_measurement,
                       MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge,
                              MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'M' THEN avg_value END)  AS air_temperature,
                       MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'M' THEN avg_value END)  AS water_temperature,
                       MAX(CASE
                               WHEN metric_name = 'PD' AND value_type = 'M'
                                   THEN value_code || ':' || avg_value::text END)                   AS precipitation_daily
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, avg_value, value_code
                      FROM metrics_hydrologicalmetric
                      WHERE value_type = 'M'
                        and metric_name in ('WLD', 'RCSA', 'IPO', 'WTO', 'ATO', 'PD')
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                      FROM estimations_water_discharge_daily
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                      FROM estimations_water_level_daily_average_with_periods
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                      FROM estimations_water_discharge_daily_average
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                      FROM estimations_water_discharge_fiveday_average
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, avg_value, NULL as value_code
                      FROM estimations_water_discharge_decade_average) AS sub
                where station_id IN (select distinct id from stations_hydrologicalstation where station_type = 'M')
                GROUP BY station_id, timestamp_local::timestamp without time zone;
            """,
            reverse_sql="DROP VIEW IF EXISTS metrics_bulk_data_hydro_manual;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW metrics_bulk_data_virtual AS
                SELECT station_id,
                        timestamp_local::timestamp without time zone,
                        MAX(CASE WHEN metric_name = 'WDD' AND value_type = 'E' THEN avg_value END)   AS discharge_daily,
                        MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge,
                        MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END) AS discharge_daily_average,
                        MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_daily_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_daily_average_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_fiveday_average_virtual
                        UNION ALL
                        SELECT station_id, timestamp_local, metric_name, value_type, avg_value
                        FROM estimations_water_discharge_decade_average_virtual) AS sub
                GROUP BY station_id, timestamp_local::timestamp without time zone;
            """,
            reverse_sql="DROP VIEW IF EXISTS metrics_bulk_data_virtual;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW metrics_bulk_data_hydro_auto AS
                SELECT station_id,
                       timestamp_local::timestamp without time zone,
                       MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN min_value END)   AS water_level_daily_min,
                       MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN avg_value END)   AS water_level_daily_average,
                       MAX(CASE WHEN metric_name = 'WLD' AND value_type = 'A' THEN max_value END)   AS water_level_daily_max,
                       MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN min_value END)   AS air_temperature_min,
                       MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN avg_value END)   AS air_temperature_average,
                       MAX(CASE WHEN metric_name = 'ATO' AND value_type = 'A' THEN max_value END)   AS air_temperature_max,
                       MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN min_value END)   AS water_temperature_min,
                       MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN avg_value END)   AS water_temperature_average,
                       MAX(CASE WHEN metric_name = 'WTO' AND value_type = 'A' THEN max_value END)   AS water_temperature_max,
                       MAX(CASE WHEN metric_name = 'WDDA' AND value_type = 'E' THEN avg_value END)  AS discharge_daily_average,
                       MAX(CASE WHEN metric_name = 'WDFA' AND value_type = 'E' THEN avg_value END)  AS fiveday_discharge,
                       MAX(CASE WHEN metric_name = 'WDDCA' AND value_type = 'E' THEN avg_value END) AS decade_discharge
                FROM (SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                      FROM metrics_hydrologicalmetric
                      WHERE value_type = 'A'
                        and metric_name in ('WLD', 'WTO', 'ATO')
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                      FROM estimations_water_discharge_daily_average
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                      FROM estimations_water_discharge_fiveday_average
                      UNION ALL
                      SELECT station_id, timestamp_local, metric_name, value_type, min_value, avg_value, max_value
                      FROM estimations_water_discharge_decade_average) AS sub
                where station_id IN (select distinct id from stations_hydrologicalstation where station_type = 'A')
                GROUP BY station_id, timestamp_local::timestamp without time zone;
            """,
            reverse_sql="DROP VIEW IF EXISTS metrics_bulk_data_hydro_auto;"
        )
    ]
