# Generated by Django 5.1.1 on 2025-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0008_update_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationsWaterLevelDailyAverageWithPeriods',
            fields=[
                ('sensor_identifier', models.CharField(blank=True, max_length=50, verbose_name='Sensor identifier')),
                ('sensor_type', models.CharField(blank=True, max_length=50, verbose_name='Sensor type')),
                ('min_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Minimum value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Maximum value')),
                ('timestamp_local', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Timestamp local without timezone')),
                ('avg_value', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Average value')),
                ('unit', models.CharField(blank=True, choices=[('cm', 'centimeter'), ('m^3/s', 'cubic meters per second'), ('degC', 'degree celsius'), ('dimensionless', 'dimensionless'), ('m^2', 'square meter'), ('mm/day', 'millimeters per day')], max_length=20, verbose_name='Unit')),
                ('value_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('E', 'Estimated'), ('I', 'Imported'), ('U', 'Unknown'), ('O', 'Override')], default='U', max_length=2, verbose_name='Value type')),
                ('metric_name', models.CharField(choices=[('WLD', 'Water level daily'), ('WLDA', 'Water level daily average'), ('WLDC', 'Water level decadal'), ('WLDCA', 'Water level decade average'), ('WDD', 'Water discharge daily'), ('WDDA', 'Water discharge daily average'), ('WDFA', 'Water discharge fiveday average'), ('WDDCA', 'Water discharge decade average'), ('WDDCAH', 'Water discharge decade average historical'), ('WTO', 'Water temperature observation'), ('ATO', 'Air temperature observation'), ('IPO', 'Ice phenomena observation'), ('PD', 'Precipitation daily'), ('WTDA', 'Water temperature daily average'), ('ATDA', 'Air temperature daily average'), ('RCSA', 'River cross section area'), ('MD', 'Maximum depth')], max_length=20, verbose_name='Metric name')),
            ],
            options={
                'db_table': 'estimations_water_level_daily_average_with_periods',
                'managed': False,
            },
        ),
    ]
