# Generated by Django 5.1.1 on 2024-12-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('timestamp_local', models.DateTimeField(verbose_name='Timestamp local without timezone')),
                ('station_id', models.PositiveIntegerField(verbose_name='Station ID')),
                ('metric_name', models.CharField(max_length=10, verbose_name='Metric name')),
                ('value_type', models.CharField(max_length=10, verbose_name='Value type')),
                ('sensor_identifier', models.CharField(blank=True, max_length=50, verbose_name='Sensor identifier')),
                ('station_type', models.CharField(choices=[('H', 'Hydro'), ('M', 'Meteo')], default='H', max_length=50, verbose_name='Station type')),
                ('previous_value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Previous value')),
                ('previous_value_code', models.IntegerField(blank=True, null=True, verbose_name='Previous code')),
                ('previous_source_type', models.CharField(choices=[('US', 'User'), ('TL', 'Telegram'), ('IN', 'Ingester'), ('UN', 'Unknown')], max_length=2, verbose_name='Previous source type')),
                ('previous_source_id', models.IntegerField(verbose_name='Previous source ID')),
                ('new_value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='New value')),
                ('new_value_code', models.IntegerField(blank=True, null=True, verbose_name='New code')),
                ('new_source_type', models.CharField(choices=[('US', 'User'), ('TL', 'Telegram'), ('IN', 'Ingester'), ('UN', 'Unknown')], max_length=2, verbose_name='New source type')),
                ('new_source_id', models.IntegerField(verbose_name='New source ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'History log entry',
                'verbose_name_plural': 'History log entries',
                'ordering': ['-created_date'],
            },
        ),
    ]
