# Generated by Django 5.0 on 2023-12-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telegram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Date created")),
                ("telegram", models.TextField(verbose_name="Original telegram(s)")),
                ("decoded_values", models.JSONField(blank=True, null=True, verbose_name="Decoded values")),
                (
                    "automatically_ingested",
                    models.BooleanField(default=False, verbose_name="Was automatically ingested?"),
                ),
                ("successfully_parsed", models.BooleanField(default=True, verbose_name="Was parsed successfully?")),
                ("errors", models.TextField(blank=True, verbose_name="Errors")),
                (
                    "hydro_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stations.hydrologicalstation",
                        verbose_name="Hydrological station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram",
                "verbose_name_plural": "Telegrams",
            },
        ),
    ]
