# Generated by Django 4.2.5 on 2023-09-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Telegram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Date created")),
                ("telegram", models.TextField(verbose_name="Original telegram(s)")),
                ("decoded_values", models.JSONField(verbose_name="Decoded values")),
                (
                    "automatically_ingested",
                    models.BooleanField(default=False, verbose_name="Was automatically ingested?"),
                ),
            ],
            options={
                "verbose_name": "Telegram",
                "verbose_name_plural": "Telegrams",
            },
        ),
    ]
