# Generated by Django 4.2.5 on 2023-09-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_uuid_index"),
        ("telegrams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
