# Generated by Django 5.0 on 2024-01-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_site_options_remove_site_name_and_more'),
        ('telegrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='meteo_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.meteorologicalstation', verbose_name='Meteorological station'),
        ),
    ]
