# Generated by Django 4.2.5 on 2023-09-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_add_default_field_and_constraint_to_sensor"),
        ("telegrams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stations.station",
                verbose_name="Station",
            ),
        ),
    ]
