# Generated by Django 4.2.5 on 2023-11-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_create_station_basin_region_relationship"),
        ("telegrams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegram",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.station",
                verbose_name="Station",
            ),
        ),
    ]
