# Generated by Django 4.2.5 on 2023-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegrams", "0002_add_station_to_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="errors",
            field=models.TextField(blank=True, verbose_name="Errors"),
        ),
        migrations.AddField(
            model_name="telegram",
            name="successfully_parsed",
            field=models.BooleanField(default=True, verbose_name="Was parsed successfully?"),
        ),
        migrations.AlterField(
            model_name="telegram",
            name="decoded_values",
            field=models.JSONField(blank=True, null=True, verbose_name="Decoded values"),
        ),
    ]
