# Generated by Django 5.0.4 on 2024-07-18 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_filestate_ingester_name'),
        ('organizations', '0002_add_discharge_norm_type_field'),
        ('telegrams', '0002_telegram_meteo_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('telegram', models.TextField(verbose_name='Original telegram')),
                ('station_code', models.CharField(blank=True, max_length=100, verbose_name='Station code')),
                ('decoded_values', models.JSONField(blank=True, null=True, verbose_name='Decoded values')),
                ('valid', models.BooleanField(default=True, verbose_name='Is telegram valid?')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram parser log',
                'verbose_name_plural': 'Telegram parser logs',
            },
        ),
        migrations.CreateModel(
            name='TelegramReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('telegram', models.TextField(verbose_name='Received telegram(s)')),
                ('valid', models.BooleanField(default=True, verbose_name='Is telegram valid?')),
                ('station_code', models.CharField(blank=True, max_length=100, verbose_name='Station code')),
                ('decoded_values', models.JSONField(blank=True, null=True, verbose_name='Decoded values')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_ts', models.DateTimeField(null=True, verbose_name='Acknowledged timestamp')),
                ('auto_stored', models.BooleanField(default=False, verbose_name='Was telegram automatically stored?')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('filestate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.filestate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Telegram received',
                'verbose_name_plural': 'Telegrams received',
            },
        ),
        migrations.CreateModel(
            name='TelegramStored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('telegram', models.TextField(verbose_name='Stored telegram(s)')),
                ('telegram_day', models.DateField(verbose_name='Telegram day')),
                ('station_code', models.CharField(max_length=100, verbose_name='Station code')),
                ('auto_stored', models.BooleanField(default=False, verbose_name='Was telegram automatically stored?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization')),
                ('stored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram stored',
                'verbose_name_plural': 'Telegrams stored',
            },
        ),
        migrations.DeleteModel(
            name='Telegram',
        ),
    ]
