# Generated by Django 5.1.1 on 2024-10-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrams', '0003_telegramparserlog_telegramreceived_telegramstored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreceived',
            name='acknowledged_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged timestamp'),
        ),
    ]
