# Generated by Django 5.0.6 on 2024-06-18 20:13

import django.db.models.deletion
import sapphire_backend.bulletins.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_add_discharge_norm_type_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('dl', 'Daily'), ('dc', 'Decadal')], default='dl', max_length=2, verbose_name='Value type')),
                ('filename', models.FileField(upload_to=sapphire_backend.bulletins.models.bulletin_upload_path, verbose_name='Bulletin file')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_templates', to='organizations.organization', to_field='uuid', verbose_name='Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_bulletin_templates', to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Bulletin template',
                'verbose_name_plural': 'Bulletin templates',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BulletinTemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag name')),
                ('description', models.TextField(verbose_name='Tag description')),
                ('type', models.CharField(choices=[('d', 'Data'), ('h', 'Header'), ('g', 'General')], default='d', max_length=2, verbose_name='Tag type')),
                ('is_default', models.BooleanField(default=True, verbose_name='Is default?')),
                ('bulletins', models.ManyToManyField(related_name='tags', to='bulletins.bulletintemplate', verbose_name='Bulletin')),
            ],
            options={
                'verbose_name': 'Bulletin template tag',
                'verbose_name_plural': 'Bulletin template tags',
            },
        ),
        migrations.AddIndex(
            model_name='bulletintemplate',
            index=models.Index(fields=['uuid'], name='bulletin_template_uuid_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulletintemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization', 'type'), name='unique_default_per_organization_and_type'),
        ),
        migrations.AddIndex(
            model_name='bulletintemplatetag',
            index=models.Index(fields=['uuid'], name='bulletin_template_tag_uuid_idx'),
        ),
    ]
