# Generated by Django 5.1 on 2024-08-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_add_secondary_name_fields_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignedStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='Assigned by')),
                ('hydro_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='stations.hydrologicalstation', to_field='uuid', verbose_name='Hydrological station')),
                ('meteo_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='stations.meteorologicalstation', to_field='uuid', verbose_name='Meteorological station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_stations', to=settings.AUTH_USER_MODEL, to_field='uuid', verbose_name='User')),
                ('virtual_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='stations.virtualstation', to_field='uuid', verbose_name='Virtual station')),
            ],
            options={
                'verbose_name': 'User assigned station',
                'verbose_name_plural': 'User assigned stations',
                'ordering': ['-created_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hydro_station__isnull', False), ('meteo_station__isnull', True), ('virtual_station__isnull', True)), models.Q(('hydro_station__isnull', True), ('meteo_station__isnull', False), ('virtual_station__isnull', True)), models.Q(('hydro_station__isnull', True), ('meteo_station__isnull', True), ('virtual_station__isnull', False)), _connector='OR'), name='only_one_station_populated')],
            },
        ),
    ]
