# Generated by Django 5.1.1 on 2025-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_assigned_station_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('regular_user', 'Regular user'), ('organization_admin', 'Organization admin'), ('super_admin', 'Super admin'), ('regime_user', 'Regime user')], default='regular_user', max_length=30, verbose_name='User role'),
        ),
    ]
