# Generated by Django 4.2.4 on 2023-08-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_add_uuid_field"),
        ("users", "0003_add_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
