# Generated by Django 4.2.4 on 2023-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_organization_related_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="user_uuid_idx"),
        ),
    ]
