# Generated by Django 4.2.5 on 2023-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_add_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")], default="en", max_length=2, verbose_name="Language"
            ),
        ),
    ]
