# Generated by Django 4.2.5 on 2023-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")], default="en", max_length=2, verbose_name="Language"
            ),
        ),
    ]
