# Generated by Django 4.2.5 on 2023-09-18 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="UUID")),
                ("name", models.CharField(default="Default", max_length=100, verbose_name="Sensor name")),
                ("manufacturer", models.CharField(blank=True, max_length=150, verbose_name="Manufacturer")),
                ("identifier", models.CharField(blank=True, max_length=150, verbose_name="Sensor identifier")),
                ("installation_date", models.DateTimeField(blank=True, null=True, verbose_name="Installation date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active?")),
            ],
            options={
                "verbose_name": "Sensor",
                "verbose_name_plural": "Sensors",
                "ordering": ["-name"],
            },
        ),
        migrations.AddField(
            model_name="station",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="UUID"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["uuid"], name="station_uuid_idx"),
        ),
        migrations.AddField(
            model_name="sensor",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stations.station", verbose_name="Station"
            ),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(fields=["uuid"], name="sensor_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(fields=["station"], name="sensor_station_idx"),
        ),
    ]
