# Generated by Django 5.0 on 2024-01-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydrologicalstation",
            name="bulletin_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Bulletin order"),
        ),
        migrations.AddField(
            model_name="meteorologicalstation",
            name="station_type",
            field=models.CharField(
                choices=[("M", "Manual"), ("A", "Automatic")], default="M", max_length=2, verbose_name="Station type"
            ),
        ),
        migrations.AlterField(
            model_name="hydrologicalstation",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hydro_stations",
                to="stations.site",
                to_field="uuid",
                verbose_name="Site",
            ),
        ),
        migrations.AlterField(
            model_name="meteorologicalstation",
            name="station_code",
            field=models.CharField(max_length=100, verbose_name="Station code"),
        ),
    ]
