# Generated by Django 4.2.5 on 2023-11-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_add_basin_and_region_models"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="basin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stations",
                to="organizations.basin",
                to_field="uuid",
                verbose_name="Basin",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regions",
                to="organizations.region",
                to_field="uuid",
                verbose_name="Region",
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["basin"], name="station_basin_idx"),
        ),
    ]
