# Generated by Django 5.0 on 2024-01-10 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.RemoveField(
            model_name='site',
            name='name',
        ),
        migrations.AddField(
            model_name='hydrologicalstation',
            name='bulletin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Bulletin order'),
        ),
        migrations.AlterField(
            model_name='hydrologicalstation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Station name'),
        ),
        migrations.AlterField(
            model_name='hydrologicalstation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hydro_stations', to='stations.site', to_field='uuid', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='meteorologicalstation',
            name='station_code',
            field=models.CharField(max_length=100, verbose_name='Station code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
    ]
