# Generated by Django 5.0 on 2024-01-09 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_hydrologicalstation_bulletin_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "Site", "verbose_name_plural": "Sites"},
        ),
        migrations.RemoveField(
            model_name="site",
            name="name",
        ),
        migrations.AlterField(
            model_name="hydrologicalstation",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Station name"),
        ),
        migrations.AlterField(
            model_name="meteorologicalstation",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Station name"),
        ),
        migrations.AlterField(
            model_name="site",
            name="latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude",
            ),
        ),
    ]
