# Generated by Django 5.0.2 on 2024-02-22 13:29

import uuid

import django.core.validators
import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('stations', '0002_alter_site_options_remove_site_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorologicalstation',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Station name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='basin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.basin', to_field='uuid', verbose_name='Basin'),
        ),
        migrations.AlterField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.organization', to_field='uuid', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.region', to_field='uuid', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='VirtualStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, null=True, verbose_name='Station timezone')),
                ('elevation', models.FloatField(blank=True, null=True, verbose_name='Elevation in meters')),
                ('name', models.CharField(max_length=150, verbose_name='Virtual station name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('station_code', models.CharField(max_length=100, verbose_name='Station code')),
                ('basin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.basin', to_field='uuid', verbose_name='Basin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.organization', to_field='uuid', verbose_name='Organization')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='organizations.region', to_field='uuid', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Virtual station',
                'verbose_name_plural': 'Virtual stations',
            },
        ),
        migrations.CreateModel(
            name='VirtualStationAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('hydro_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.hydrologicalstation', verbose_name='Hydrological station')),
                ('virtual_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.virtualstation', verbose_name='Virtual station')),
            ],
            options={
                'verbose_name': 'Virtual station association',
                'verbose_name_plural': 'Virtual station associations',
            },
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='hydro_stations',
            field=models.ManyToManyField(related_name='virtual_stations', through='stations.VirtualStationAssociation', to='stations.hydrologicalstation'),
        ),
        migrations.AddIndex(
            model_name='virtualstation',
            index=models.Index(models.F('uuid'), name='virtual_station_uuid_idx'),
        ),
    ]
