# Generated by Django 4.2.5 on 2023-09-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_uuid_index"),
        ("stations", "0002_add_sensor_model_and_uuid_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="is_default",
            field=models.BooleanField(default=True, verbose_name="Is default?"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensors",
                to="stations.station",
                verbose_name="Station",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stations",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("station", "is_default"),
                name="unique_default_sensor_per_station",
            ),
        ),
    ]
