# Generated by Django 4.2.6 on 2023-11-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations", "0002_create_station_basin_region_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Date created")),
                ("last_modified", models.DateTimeField(auto_now=True, verbose_name="Modified date")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="stations.station",
                        to_field="uuid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remarks",
                        to=settings.AUTH_USER_MODEL,
                        to_field="uuid",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remark",
                "verbose_name_plural": "Remarks",
                "ordering": ["-last_modified"],
            },
        ),
    ]
