# Generated by Django 5.0.4 on 2024-04-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_add_virtual_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrologicalstation',
            name='decadal_discharge_norm',
        ),
        migrations.RemoveField(
            model_name='hydrologicalstation',
            name='monthly_discharge_norm',
        ),
    ]
