# Generated by Django 5.0.6 on 2024-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_remove_norm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='meteorologicalstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='bulletin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Bulletin order'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='discharge_level_alarm',
            field=models.FloatField(blank=True, null=True, verbose_name='Dangerous discharge level'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='historical_discharge_maximum',
            field=models.FloatField(blank=True, null=True, verbose_name='Historical maximal value of discharge'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='historical_discharge_minimum',
            field=models.FloatField(blank=True, null=True, verbose_name='Historical minimal value of discharge'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
    ]
