# Generated by Django 5.0.6 on 2024-08-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_remove_norm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='meteorologicalstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='bulletin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Bulletin order'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secondary name'),
        ),
    ]
