# Generated by Django 5.1 on 2024-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_add_secondary_name_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualstation',
            name='daily_forecast',
            field=models.BooleanField(default=False, verbose_name='Enable daily forecast'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='decadal_forecast',
            field=models.BooleanField(default=False, verbose_name='Enable decadal forecast'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='monthly_forecast',
            field=models.BooleanField(default=False, verbose_name='Enable monthly forecast'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='pentad_forecast',
            field=models.BooleanField(default=False, verbose_name='Enable pentad forecast'),
        ),
        migrations.AddField(
            model_name='virtualstation',
            name='seasonal_forecast',
            field=models.BooleanField(default=False, verbose_name='Enable seasonal forecast'),
        ),
    ]
