# Generated by Django 5.1.1 on 2024-11-19 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_virtualstation_daily_forecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('water_level_min', models.FloatField(blank=True, help_text='Lower bound of water level axis in all charts', null=True, verbose_name='Water level minimum')),
                ('water_level_max', models.FloatField(blank=True, help_text='Upper bound of water level axis in all charts', null=True, verbose_name='Water level maximum')),
                ('discharge_min', models.FloatField(blank=True, help_text='Lower bound of discharge axis in rating curve charts', null=True, verbose_name='Discharge minimum')),
                ('discharge_max', models.FloatField(blank=True, help_text='Upper bound of discharge axis in rating curve charts', null=True, verbose_name='Discharge maximum')),
                ('cross_section_min', models.FloatField(blank=True, help_text='Lower bound of cross section area axis in cross section charts', null=True, verbose_name='Cross section area minimum')),
                ('cross_section_max', models.FloatField(blank=True, help_text='Upper bound of cross section area axis in cross section charts', null=True, verbose_name='Cross section area maximum')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_settings', to='stations.hydrologicalstation', to_field='uuid', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station chart settings',
                'verbose_name_plural': 'Station chart settings',
                'indexes': [models.Index(models.F('uuid'), name='station_chart_stngs_uuid_idx')],
            },
        ),
    ]
