# Generated by Django 5.1.1 on 2025-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_add_chart_settings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrologicalstation',
            name='historical_water_level_maximum',
            field=models.FloatField(blank=True, null=True, verbose_name='Historical maximal value of water level'),
        ),
        migrations.AddField(
            model_name='hydrologicalstation',
            name='historical_water_level_minimum',
            field=models.FloatField(blank=True, null=True, verbose_name='Historical minimal value of water level'),
        ),
        migrations.AddField(
            model_name='hydrologicalstation',
            name='water_level_alarm',
            field=models.FloatField(blank=True, null=True, verbose_name='Dangerous water level'),
        ),
    ]
