# Generated by Django 4.2.5 on 2023-09-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False, verbose_name="Timestamp")),
                ("value", models.DecimalField(decimal_places=5, max_digits=10, verbose_name="Value")),
                ("metric", models.CharField(max_length=30, verbose_name="Metric")),
                ("unit", models.CharField(blank=True, max_length=20, verbose_name="Unit")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stations.station", verbose_name="Station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
                "db_table": "measurement_measurements",
                "managed": False,  # manually change to False after the migration was run
            },
        ),
    ]
