# Generated by Django 5.0.4 on 2024-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True, verbose_name='Original remote filename')),
                ('remote_path', models.TextField(verbose_name='File path on the remote location')),
                ('local_path', models.TextField(blank=True, null=True, verbose_name='Local file path')),
                ('state_timestamp', models.DateTimeField(verbose_name='Timestamp with timezone')),
                ('state', models.CharField(choices=[('discovered', 'Discovered'), ('downloaded', 'Downloaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='discovered', verbose_name='State name')),
            ],
            options={
                'verbose_name': 'File state',
                'verbose_name_plural': 'File states',
            },
        ),
    ]
