# Generated by Django 5.0.4 on 2024-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestate',
            name='ingester_name',
            field=models.TextField(default='imomo_auto', verbose_name='Ingester name'),
            preserve_default=False,
        ),
    ]
